### ISSUE TITLE
Deprecation warning due to an old version of ember-cli-htmlbars

### ISSUE THREAD

**Issue by arnaudbesnier** [ChrisHonniball/ember-highlight-code#4]
Hi,

Here is the warning, I have when I start my ember app using your package:

```
DEPRECATION: Overriding init without calling this._super is deprecated. Please call `this._super.init && this._super.init.apply(this, arguments);` addon: `ember-cli-htmlbars`
```

This warning is generated by an old version of `ember-cli-htmlbars` you use (0.7.9).
Can you update to a version 1.x to make it disappear.

See more info in this issue: https://github.com/ember-cli/ember-cli-htmlbars/issues/77

Thank you!

**Comment by arnaudbesnier** [comment]
Hey @ChrisHonniball , I would really love this small change. Do you have 5 minutes to update your package?

**Comment by ChrisHonniball** [comment]
I haven't visited this add-on in a while but I'm hoping to find some time soon to update this to Ember 2.10.0. If you'd like to tackle it and submit a PR that would help too. Sorry for the slow response.

**Comment by ChrisHonniball** [comment]
Does the 0.0.9 update help this?

**Comment by arnaudbesnier** [comment]
@ChrisHonniball the warning has disappeared, thank you!
